[project]
name = "olake-webinar-presentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.10.1",
    "qrcode[pil]>=8.2",
]
